/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src.utilities;

public class App {

    public static void main(final String[] args) {
        Menu menu = new Menu();
        menu.showGameMenu();
    }
}


