/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src.utilities;

public class App {
    public static void main(String[] args) {
        System.out.println("hola mundo");
    }
}
