/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src;

public class App {
    private static void main(final String[] args) {
        System.out.println("hola mundo");
    }
}
